# Ubuntu Server QA Jenkins Jobs
# Copyright (C) 2016 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version..
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

- project:
    name: cloud-init
    jobs:
      - cloud-init-copr-build
      - cloud-init-copr-test-7
      - cloud-init-github-mirror
      - cloud-init-integration-ec2-b
      - cloud-init-integration-ec2-e
      - cloud-init-integration-ec2-x
      - cloud-init-integration-ec2-terminate
      - cloud-init-integration-lxd-b
      - cloud-init-integration-lxd-e
      - cloud-init-integration-lxd-x
      - cloud-init-integration-nocloud-kvm-b
      - cloud-init-integration-nocloud-kvm-e
      - cloud-init-integration-nocloud-kvm-x
      - cloud-init-integration-proposed-b-ec2
      - cloud-init-integration-proposed-b-lxd
      - cloud-init-integration-proposed-b-kvm
      - cloud-init-integration-proposed-e-ec2
      - cloud-init-integration-proposed-e-lxd
      - cloud-init-integration-proposed-e-kvm
      - cloud-init-integration-proposed-x-ec2
      - cloud-init-integration-proposed-x-lxd
      - cloud-init-integration-proposed-x-kvm
      - cloud-init-integration-proposed-trigger-b
      - cloud-init-integration-proposed-trigger-e
      - cloud-init-integration-proposed-trigger-x
      - cloud-init-lp-build-status
      - cloud-init-style-tip

- defaults:
    name: global
    description: |
      Cloud-init Ubuntu Server QA Jenkins Job

      *** STOP ***
      Do NOT edit this job through the web
      This job is managed by Jenkins Job Builder and stored on Github via the URL below:
      https://github.com/CanonicalLtd/server-jenkins-jobs
      *** STOP ***
    properties:
      - build-discarder:
          num-to-keep: 3
    publishers:
      - email-server-crew

- publisher:
    name: email-server-crew
    publishers:
      - email:
          recipients: server-crew-qa@lists.canonical.com

- publisher:
    name: archive-results
    publishers:
      - archive:
          artifacts: 'cloud-init/results/**'
