# Ubuntu Server QA Jenkins Jobs
# Copyright (C) 2016 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version..
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

- job:
    name: cloud-init-integration-lxd-x
    node: torkoal
    triggers:
      - timed: "H 11 * * *"
    publishers:
      - email-server-crew
      - archive-results
      - trigger:
          project: cloud-init-integration-lxd-b
          threshold: FAILURE
    builders:
      - integration-lxd:
          release: xenial

- job:
    name: cloud-init-integration-lxd-b
    node: torkoal
    publishers:
      - email-server-crew
      - archive-results
      - trigger:
          project: cloud-init-integration-lxd-c
          threshold: FAILURE
    builders:
      - integration-lxd:
          release: bionic

- job:
    name: cloud-init-integration-lxd-c
    node: torkoal
    publishers:
      - email-server-crew
      - archive-results
    builders:
      - integration-lxd:
          release: cosmic

- builder:
    name: integration-lxd
    builders:
      - shell: |
          release="{release}"

          sudo rm -Rf *
          git clone https://github.com/CanonicalLtd/server-test-scripts.git
          git clone https://git.launchpad.net/cloud-init
          cd cloud-init
          ../server-test-scripts/cloud-init/daily_deb.sh -v $release
          tox -e citest -- run --os-name $release \
            --platform lxd --preserve-data --data-dir results \
            --verbose --deb cloud-init_*_all.deb
