# Ubuntu Server QA Jenkins Jobs
# Copyright (C) 2016 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version..
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

- job:
    name: cloud-init-integration-proposed-trigger-x
    node: torkoal
    triggers:
      - timed: "H 10 * * *"
    builders:
      - trigger-proposed-integration:
          release: xenial
          triggerwhat: cloud-init-integration-proposed-x-lxd cloud-init-integration-proposed-x-ec2 cloud-init-integration-proposed-x-kvm

- job:
    name: cloud-init-integration-proposed-x-ec2
    node: torkoal
    auth-token: BUILD_ME
    publishers:
        - email-server-crew
        - archive-results
    builders:
      - proposed-integration:
          release: xenial
          release-ver: 16.04
          platform: ec2

- job:
    name: cloud-init-integration-proposed-x-lxd
    node: torkoal
    auth-token: BUILD_ME
    publishers:
        - email-server-crew
        - archive-results
    builders:
      - proposed-integration:
          release: xenial
          release-ver: 16.04
          platform: lxd

- job:
    name: cloud-init-integration-proposed-x-kvm
    node: torkoal
    auth-token: BUILD_ME
    publishers:
        - email-server-crew
        - archive-results
    builders:
      - proposed-integration:
          release: xenial
          release-ver: 16.04
          platform: nocloud-kvm

- job:
    name: cloud-init-integration-proposed-trigger-b
    node: torkoal
    publishers: []
    triggers:
      - timed: "H 10 * * *"
    builders:
      - trigger-proposed-integration:
          release: bionic
          triggerwhat: cloud-init-integration-proposed-b-lxd cloud-init-integration-proposed-b-ec2 cloud-init-integration-proposed-b-kvm

- job:
    name: cloud-init-integration-proposed-b-ec2
    node: torkoal
    auth-token: BUILD_ME
    builders:
      - proposed-integration:
          release: bionic
          release-ver: 18.04
          platform: ec2
    publishers:
        - email-server-crew
        - archive-results

- job:
    name: cloud-init-integration-proposed-b-lxd
    node: torkoal
    auth-token: BUILD_ME
    builders:
      - proposed-integration:
          release: bionic
          release-ver: 18.04
          platform: lxd
    publishers:
        - email-server-crew
        - archive-results

- job:
    name: cloud-init-integration-proposed-b-kvm
    node: torkoal
    auth-token: BUILD_ME
    builders:
      - proposed-integration:
          release: bionic
          release-ver: 18.04
          platform: nocloud-kvm
    publishers:
        - email-server-crew
        - archive-results

- job:
    name: cloud-init-integration-proposed-trigger-e
    node: torkoal
    publishers: []
    triggers:
      - timed: "H 10 * * *"
    builders:
      - trigger-proposed-integration:
          release: eoan
          triggerwhat: cloud-init-integration-proposed-e-lxd cloud-init-integration-proposed-e-ec2 cloud-init-integration-proposed-e-kvm

- job:
    name: cloud-init-integration-proposed-e-kvm
    node: torkoal
    auth-token: BUILD_ME
    builders:
      - proposed-integration:
          release: eoan
          release-ver: 19.10
          platform: nocloud-kvm
    publishers:
        - email-server-crew
        - archive-results

- job:
    name: cloud-init-integration-proposed-e-lxd
    node: torkoal
    auth-token: BUILD_ME
    builders:
      - proposed-integration:
          release: eoan
          release-ver: 19.10
          platform: lxd
    publishers:
        - email-server-crew
        - archive-results

- job:
    name: cloud-init-integration-proposed-e-ec2
    node: torkoal
    auth-token: BUILD_ME
    builders:
      - proposed-integration:
          release: eoan
          release-ver: 19.10
          platform: ec2
    publishers:
        - email-server-crew
        - archive-results

- job:
    name: cloud-init-integration-proposed-f-kvm
    node: torkoal
    auth-token: BUILD_ME
    builders:
      - proposed-integration:
          release: focal
          release-ver: 20.04
          platform: nocloud-kvm
    publishers:
        - email-server-crew
        - archive-results

- job:
    name: cloud-init-integration-proposed-f-lxd
    node: torkoal
    auth-token: BUILD_ME
    builders:
      - proposed-integration:
          release: focal
          release-ver: 20.04
          platform: lxd
    publishers:
        - email-server-crew
        - archive-results

- job:
    name: cloud-init-integration-proposed-trigger-f
    node: torkoal
    publishers: []
    triggers:
      - timed: "H 10 * * *"
    builders:
      - trigger-proposed-integration:
          release: eoan
          triggerwhat: cloud-init-integration-proposed-f-lxd cloud-init-integration-proposed-f-ec2 cloud-init-integration-proposed-f-kvm


- job:
    name: cloud-init-integration-proposed-f-ec2
    node: torkoal
    auth-token: BUILD_ME
    builders:
      - proposed-integration:
          release: focal
          release-ver: 20.04
          platform: ec2
    publishers:
        - email-server-crew
        - archive-results

- builder:
    name: proposed-integration
    builders:
      - shell: |
          release="{release}"
          release_ver="{release-ver}"
          platform="{platform}"

          set -e
          sudo rm -Rf cloud-init
          git clone https://git.launchpad.net/cloud-init
          cd cloud-init
          tag=$(git tag --list | grep "$release_ver" | tail -1)
          echo "Running with source from tag $tag"
          git checkout $tag
          mirror="http://archive.ubuntu.com/ubuntu/"
          if [ -z "$TMPDIR" -a "$(hostname)" = "torkoal" ]; then
              export TMPDIR=/var/lib/jenkins/tmp/
          fi
          set +e
          no_proxy=launchpad.net https_proxy="http://squid.internal:3128" tox \
              -e citest -- run \
              --os-name="$release" \
              --platform=$platform \
              --repo=\'deb $mirror $release-proposed main\' \
              --preserve-data --data-dir="./results" \
              --verbose
          rc="$?"
          # on success remove large artifacts
          if [ "$rc" = 0 ]; then
            find ./results -type f \
                \( -name '*.qcow2' -o -name '*.img' -o -name '*.log' \) -delete
          fi

          # remove temporary keys
          find . -name "id_rsa*" -delete

          exit $rc

- builder:
    name: trigger-proposed-integration
    builders:
      - shell: |
          #!/bin/bash
          set -ex
          sudo rm -rf *

          rel={release}
          triggerwhat="{triggerwhat}"
          pkg="cloud-init"

          git clone https://github.com/canonical/server-test-scripts
          cd server-test-scripts/launchpad/
          proposed=$(./version_lookup.py -r $rel -p Proposed -s Published $pkg)
          updates=$(./version_lookup.py -r $rel -p Updates -s Published $pkg)
          # output is <pkg>,<rel>,<pocket>,<state>,<version>
          pver=$(echo "$proposed" | sed "s/.*,//")
          uver=$(echo "$updates" | sed "s/.*,//")
          if [ -z "$proposed" ]; then
            echo "no $pkg in proposed"
            exit 0
          elif [ "$uver" = "$pver" ]; then
            echo "$pkg in proposed == updates == $pver. no need to test."
            exit 0
          fi

          for t in $triggerwhat; do
              curl -X POST --netrc-file $JENKINS_HOME/jenkins-bot-creds http://server-team-jenkins-be.internal:8080/server/job/$t/build?token=BUILD_ME
          done
