# Ubuntu Server QA Jenkins Jobs
# Copyright (C) 2016 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version..
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

- job:
    name: cloud-init-style-tip
    defaults: cloud-init
    node: metal-amd64
    triggers:
      - timed: "H 23 * * *"
    builders:
      - shell: |
          #!/bin/bash
          set -e
          rm -rf *

          export https_proxy="http://squid.internal:3128"
          export no_proxy=launchpad.net

          git clone https://git.launchpad.net/cloud-init
          cd cloud-init
          tox -e tip-flake8
          tox -e tip-pylint

- job:
    name: cloud-init-lp-build-status
    defaults: cloud-init
    node: metal-amd64
    triggers:
      - timed: "H */5 * * *"
    publishers:
      - email-server-crew-qa
      - junit:
          results: server-test-scripts/cloud-init/results.xml
    builders:
      - shell: |
          #!/bin/bash
          set -e
          rm -rf *
          git clone https://github.com/canonical/server-test-scripts
          cd server-test-scripts/cloud-init
          ./lp_build_status.py
          cat results.xml

- job:
    name: cloud-init-github-mirror
    defaults: cloud-init
    node: metal-amd64
    triggers:
      - timed: "H */4 * * *"
    builders:
      - shell: |
          #!/bin/bash
          set -eux
          MIRROR_DIR="mirror"

          if [ -d "$MIRROR_DIR" ]; then
              rm -rf "$MIRROR_DIR"
          fi

          GIT_SSH_COMMAND='ssh -i $HOME/.ssh/cloudinit_id_rsa' git clone --mirror git@github.com:canonical/cloud-init.git "$MIRROR_DIR"
          cd "$MIRROR_DIR" || exit 1

          git remote add launchpad git+ssh://server-team-bot@git.launchpad.net/cloud-init
          GIT_SSH_COMMAND='ssh -i $HOME/.ssh/cloudinit_id_rsa' git fetch -q
          git push -q --mirror launchpad
